version: "3.9"
services:
  mysql8:
     image: mysql:8
     ports:
      - "3307:3306"
     environment:
      MYSQL_ROOT_PASSWORD: DB_PASSWORD
      MYSQL_DATABASE: DB_DATABASE
     volumes:
      - data-mysql:/var/lib/mysql
     restart: always
     networks: 
      - spring  
       
  postgres14:
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: DB_PASSWORD
      POSTGRES_DB: DB_DATABASE 
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always    
    networks:
      - spring  

  api-principal:
    build:
      context: ./api-Principal
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file: ./api-Principal/.env
    networks:
      - spring
    depends_on:
      - mysql8
      - servidor-stock
       
    restart: always        


  servidor-stock:
    build:
      context: ./servicio-control-stock
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./servicio-control-stock/.env
    networks:
      - spring
    depends_on:
      - postgres14
    restart: always    



volumes:
  data-mysql:    
  data-postgres: 

networks:
  spring: